theme = "rose_pine_dawn"

[editor]
gutters = ["diagnostics", "spacer", "diff"]
color-modes = true

[editor.cursor-shape]
insert = "bar"
select = "underline"

[editor.statusline]
mode.normal = "N"
mode.insert = "I"
mode.select = "S"
right = ["selections", "position", "total-line-numbers"]

[editor.indent-guides]
render = true

[editor.search]
smart-case = false

[editor.whitespace.render]
space = "none"
tab = "all"
newline = "all"

[editor.whitespace.characters]
tab = "→"
newline = "⏎"
tabpad = "→"

[keys.normal]
C-q = ":quit-all"
C-s = ":w"
A-s = "save_selection"
esc = ["collapse_selection", "keep_primary_selection"]
# Because A-left/right doesn't work on my keyboard
S-up = "expand_selection"
S-down = "shrink_selection"
S-left = "select_prev_sibling"
S-right = "select_next_sibling"

[keys.insert]
C-s = ":w"

[keys.normal.g]
left = "goto_line_start"
right = "goto_line_end"

[keys.select.g]
left = "goto_line_start"
right = "goto_line_end" 

# I just want \ to be windows mode, but there's no shortcut for window mode so I copied it in
[keys.normal."\\"]
"\\" = "rotate_view"
v = "vsplit"
s = "hsplit"
left = "jump_view_left"
right = "jump_view_right"
k = "jump_view_up"
j = "jump_view_down"
o = "wonly"
q = "wclose"
"S-left" = "swap_view_left"
"S-right" = "swap_view_right"
K = "swap_view_up"
J = "swap_view_down"

