theme = "rose_pine_dawn"

[editor]
gutters = ["diagnostics", "spacer", "diff"]
color-modes = true

[editor.cursor-shape]
insert = "bar"
select = "underline"

[editor.statusline]
mode.normal = "N"
mode.insert = "I"
mode.select = "S"
right = ["selections", "position", "total-line-numbers"]

[editor.indent-guides]
render = true

[editor.search]
smart-case = false

[keys.normal]
C-q = ":quit-all"

[keys.insert]
C-s = ":w"

[keys.normal.g]
left = "goto_line_start"
right = "goto_line_end"

[keys.select.g]
left = "goto_line_start"
right = "goto_line_end" 

[keys.normal."\\"]
"\\" = "rotate_view"
v = "vsplit"
s = "hsplit"
left = "jump_view_left"
right = "jump_view_right"
k = "jump_view_up"
j = "jump_view_down"
o = "wonly"
q = "wclose"
"S-left" = "swap_view_left"
"S-right" = "swap_view_right"
K = "swap_view_up"
J = "swap_view_down"
