[[language]]
name = 'tsx'
auto-format = true
formatter = {command = 'npx', args = ['prettier', '--stdin', '--parser', 'typescript']}


[[language]]
name = 'typescript'
auto-format = true
formatter = {command = 'npx', args = ['prettier', '--stdin', '--parser', 'typescript']}

[[language]]
name = 'python'
auto-format = true
formatter = {command = 'poetry', args = ['run', 'ruff', 'format', '-']}

[[language]]
name = 'inko'
auto-format = true
scope = "source.inko"
file-types = ["inko"]
comment-token = "#"
indent = { tab-width = 2, unit = " "}
roots = ["src"]
