[[language]]
name = 'tsx'
formatter = {command = 'npx', args = ['prettier', '--stdin', '--parser', 'typescript']}


[[language]]
name = 'typescript'
formatter = {command = 'npx', args = ['prettier', '--stdin', '--parser', 'typescript']}

[[language]]
name = 'python'
formatter = {command = 'poetry', args = ['run', 'black', '-l', '100', '-']}

